services:
  - type: web
    name: dxai-solutions
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn -w 1 -k uvicorn.workers.UvicornWorker --timeout 120 --bind 0.0.0.0:$PORT src.api.main:app"
    healthCheckPath: "/"
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.16"
      - key: WEB_CONCURRENCY # Set to 1 for free tier
        value: 1
      # Note: All secret keys and other environment variables
      # will be loaded from a .env file configured as a Secret File in the Render Dashboard.
